apiVersion: v1
kind: Namespace
metadata:
  name: fabrik-otel
  labels:
    name: fabrik-otel
    instrumentation: opentelemetry
    dynatrace.com/enrich: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: fabrik-oneagent
  labels:
    name: fabrik-oneagent
    instrumentation: oneagent
    dynatrace.com/inject: "true"
