apiVersion: apps/v1
kind: Deployment
metadata:
  name: fabrik-service
  namespace: fabrik-oneagent
  labels:
    app: fabrik-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fabrik-service
  template:
    metadata:
      labels:
        app: fabrik-service
    spec:
      containers:
      - name: fabrik-service
        image: ghcr.io/mreider/fabrik-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: REDIS_HOST
          value: "redis.fabrik-oneagent"
        - name: REDIS_PORT
          value: "6379"
        - name: DYNATRACE_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: dynatrace-secret
              key: endpoint
        - name: DYNATRACE_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: dynatrace-secret
              key: api-token
        resources:
          limits:
            cpu: "400m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: fabrik-service
  namespace: fabrik-oneagent
spec:
  selector:
    app: fabrik-service
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
