spring.application.name=shipping-receiver
server.port=8083
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}
spring.kafka.consumer.group-id=shipping-group
spring.kafka.consumer.auto-offset-reset=earliest
grpc.client.shipping-processor.address=static://${SHIPPING_PROCESSOR_HOST}:9090
grpc.client.shipping-processor.negotiation-type=plaintext
