name: Build and Push Docker Images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  OWNER: mreider

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push fabrik-proxy image
        uses: docker/build-push-action@v4
        with:
          context: ./src/fabrik-proxy
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.OWNER }}/fabrik-proxy:latest

      - name: Build and push fabrik-service image
        uses: docker/build-push-action@v4
        with:
          context: ./src/fabrik-service
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.OWNER }}/fabrik-service:latest
